### ISSUE TITLE
Destination/SalesforceCRM

### ISSUE THREAD

**Issue by subintp** [Multiwoven/multiwoven-integrations#8]

**Comment by karthik-sivadas** [comment]
Note: The current implementation only has Account object integration. We need to add a catalogue for all the objects given in the [documentation](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_list.htm). Also need to test the upsert and fix the bug for delete action which currently has `id` instead of `Id`.
